/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "./logo.jpg",
        "heroText": "叫兽 前端",
        "tagline": "文档 笔记",
        "actionText": "点击进入 →",
        "actionLink": "/Frontend/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-0ef745b4",
      "path": "/"
    },
    {
      "title": "前端",
      "frontmatter": {
        "title": "前端",
        "sidebar": "auto"
      },
      "regularPath": "/Frontend/",
      "relativePath": "Frontend/README.md",
      "key": "v-42d6d252",
      "path": "/Frontend/",
      "headers": [
        {
          "level": 2,
          "title": "温馨提示",
          "slug": "温馨提示"
        },
        {
          "level": 2,
          "title": "前端知识点",
          "slug": "前端知识点"
        },
        {
          "level": 3,
          "title": "1. HTML",
          "slug": "_1-html"
        }
      ]
    },
    {
      "title": "工具",
      "frontmatter": {
        "title": "工具",
        "sidebar": "auto"
      },
      "regularPath": "/Tools/",
      "relativePath": "Tools/README.md",
      "key": "v-5c0c3b89",
      "path": "/Tools/"
    }
  ],
  "themeConfig": {
    "logo": "/logo.jpg",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "前端",
        "link": "/Frontend/"
      },
      {
        "text": "工具",
        "link": "/Tools/"
      }
    ]
  }
}